name: autoroll chromium
on:
  schedule:
    - cron: '0 11 * * *'
  push:
    paths:
      - '.github/workflows/autoroll-chromium.yml'
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/autoroll-chromium.yml'
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: microsoft/playwright-github-action@v1
      - name: setup git credentials
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      - name: prepare checkout
        run: node cronjobs/autoroll-chromium/prepare.js
      - name: find_revision
        run: node cronjobs/autoroll-chromium/find_revision.js
      - name: build chromium
        run: node cronjobs/autoroll-chromium/build.js
      - name: test chromium build
        run: node cronjobs/autoroll-chromium/test.js

