name: autoroll webkit
on:
  schedule:
    - cron: '0 11 * * *'
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: microsoft/playwright-github-action@v1
      - name: setup git credentials
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      - name: install webkit dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libharfbuzz-dev libepoxy-dev libgcrypt-dev libsoup2.4-dev libwebp-dev flatpak
      - name: prepare checkout
        run: node cronjobs/autoroll-webkit/prepare.js
      - name: rebase
        run: node cronjobs/autoroll-webkit/rebase.js
      - name: build webkit
        run: node cronjobs/autoroll-webkit/build.js
      - name: test webkit build
        run: node cronjobs/autoroll-webkit/test.js

