name: experimental
on:
  release:
    types: [published]
  push:
    branches:
      - master
    tags:
      - *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - run: echo $FOOBAR
        env:
          FOOBAR: ${{ github.ref }}

