name: experimental
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - run: echo $FOOBAR
        env:
          FOOBAR: ${{ job.container.id }}

