name: track docker size
on:
  schedule:
    - cron: '0 11 * * *'
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: node cronjobs/track-docker-image-size/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

